import { BuildingDef, BuildingId } from '../types';

export const BUILDINGS_CATALOG: Record<BuildingId, BuildingDef> = {
  road: {
    id: 'road',
    name: 'Estrada Pavimentada',
    category: 'transport',
    cost: 10,
    monthlyUpkeep: 1,
    description: 'Conecta zonas, serviços e permite circulação de veículos e transeuntes.',
    iconName: 'Route',
    size: 1,
  },
  power_line: {
    id: 'power_line',
    name: 'Linha de Alta Tensão',
    category: 'power',
    cost: 5,
    monthlyUpkeep: 1,
    description: 'Conduz eletricidade entre áreas distantes da cidade.',
    iconName: 'Zap',
    size: 1,
  },
  water_pipe: {
    id: 'water_pipe',
    name: 'Canalização Subterrânea',
    category: 'water',
    cost: 5,
    monthlyUpkeep: 1,
    description: 'Leva água potável para os bairros e indústrias.',
    iconName: 'Droplet',
    size: 1,
  },
  // Power Plants
  wind_turbine: {
    id: 'wind_turbine',
    name: 'Turbina Eólica',
    category: 'power',
    cost: 500,
    monthlyUpkeep: 15,
    powerProduced: 75,
    pollutionProduced: 0,
    radiusEffect: 8,
    description: 'Energia 100% limpa e renovável. Ideal para pequenas comunidades sustentáveis.',
    iconName: 'Wind',
    size: 1,
  },
  coal_plant: {
    id: 'coal_plant',
    name: 'Usina Termelétrica a Carvão',
    category: 'power',
    cost: 2500,
    monthlyUpkeep: 85,
    powerProduced: 500,
    pollutionProduced: 45,
    radiusEffect: 12,
    description: 'Gera grande volume de eletricidade, mas polui pesadamente o ar ao redor.',
    iconName: 'Flame',
    size: 2,
  },
  solar_plant: {
    id: 'solar_plant',
    name: 'Parque de Energia Solar',
    category: 'power',
    cost: 1500,
    monthlyUpkeep: 35,
    powerProduced: 220,
    pollutionProduced: 0,
    radiusEffect: 10,
    description: 'Fonte solar moderna, limpa e confiável com baixa taxa de manutenção.',
    iconName: 'Sun',
    size: 2,
  },
  nuclear_plant: {
    id: 'nuclear_plant',
    name: 'Usina Termonuclear',
    category: 'power',
    cost: 8000,
    monthlyUpkeep: 300,
    powerProduced: 2000,
    pollutionProduced: 5,
    radiusEffect: 18,
    description: 'Altíssima capacidade para alimentar grandes metrópoles.',
    iconName: 'Atom',
    size: 2,
  },
  // Water
  water_tower: {
    id: 'water_tower',
    name: 'Torre Caixa d\'Água',
    category: 'water',
    cost: 350,
    monthlyUpkeep: 12,
    waterProduced: 150,
    pollutionProduced: 0,
    radiusEffect: 9,
    description: 'Armazena e distribui água sob pressão com baixo custo de instalação.',
    iconName: 'Cylinder',
    size: 1,
  },
  water_pump: {
    id: 'water_pump',
    name: 'Estação de Bombeamento Fluvial',
    category: 'water',
    cost: 1100,
    monthlyUpkeep: 45,
    waterProduced: 600,
    pollutionProduced: 2,
    radiusEffect: 14,
    description: 'Retira e purifica água doce de rios ou lençóis para toda a região.',
    iconName: 'Waves',
    size: 1,
  },
  // Emergency & Services
  police_station: {
    id: 'police_station',
    name: 'Delegacia de Polícia',
    category: 'emergency',
    cost: 650,
    monthlyUpkeep: 50,
    powerConsumed: 10,
    waterConsumed: 8,
    policeCoverage: 80,
    radiusEffect: 12,
    description: 'Reduz a criminalidade e traz segurança para os moradores e lojistas.',
    iconName: 'Shield',
    size: 1,
  },
  fire_station: {
    id: 'fire_station',
    name: 'Corpo de Bombeiros',
    category: 'emergency',
    cost: 650,
    monthlyUpkeep: 50,
    powerConsumed: 10,
    waterConsumed: 12,
    fireCoverage: 85,
    radiusEffect: 12,
    description: 'Combate incêndios rapidamente e previne tragédias urbanas.',
    iconName: 'FlameKindling',
    size: 1,
  },
  hospital: {
    id: 'hospital',
    name: 'Hospital Geral Municipal',
    category: 'education_health',
    cost: 1400,
    monthlyUpkeep: 100,
    powerConsumed: 25,
    waterConsumed: 20,
    healthCoverage: 90,
    radiusEffect: 16,
    description: 'Aumenta a expectativa de vida, cura doentes e atrai novos cidadãos.',
    iconName: 'HeartPulse',
    size: 2,
  },
  elementary_school: {
    id: 'elementary_school',
    name: 'Escola Municipal de Base',
    category: 'education_health',
    cost: 500,
    monthlyUpkeep: 40,
    powerConsumed: 12,
    waterConsumed: 10,
    educationCoverage: 70,
    radiusEffect: 10,
    description: 'Educação básica essencial que eleva a produtividade e reduz o crime.',
    iconName: 'GraduationCap',
    size: 1,
  },
  high_school: {
    id: 'high_school',
    name: 'Colégio Técnico e Ensino Médio',
    category: 'education_health',
    cost: 1100,
    monthlyUpkeep: 75,
    powerConsumed: 20,
    waterConsumed: 15,
    educationCoverage: 85,
    radiusEffect: 14,
    description: 'Qualifica a força de trabalho para indústrias de alta tecnologia e serviços.',
    iconName: 'BookOpen',
    size: 2,
  },
  // Parks & Leisure
  small_park: {
    id: 'small_park',
    name: 'Praça de Bairro com Jardim',
    category: 'parks',
    cost: 120,
    monthlyUpkeep: 6,
    powerConsumed: 1,
    waterConsumed: 4,
    parkEffect: 30,
    radiusEffect: 6,
    description: 'Área verde relaxante com bancos, árvores e flores que valoriza os terrenos.',
    iconName: 'Trees',
    size: 1,
  },
  large_park: {
    id: 'large_park',
    name: 'Parque Urbano Municipal',
    category: 'parks',
    cost: 500,
    monthlyUpkeep: 25,
    powerConsumed: 3,
    waterConsumed: 12,
    parkEffect: 60,
    radiusEffect: 11,
    description: 'Lago ornamental, pistas de caminhada e ar puro para toda a vizinhança.',
    iconName: 'TreePine',
    size: 2,
  },
  fountain_plaza: {
    id: 'fountain_plaza',
    name: 'Praça Central com Chafariz',
    category: 'parks',
    cost: 300,
    monthlyUpkeep: 15,
    powerConsumed: 4,
    waterConsumed: 15,
    parkEffect: 45,
    radiusEffect: 8,
    description: 'Ponto de encontro vibrante com chafariz iluminado e comércio ao redor.',
    iconName: 'Sparkles',
    size: 1,
  },
  sports_stadium: {
    id: 'sports_stadium',
    name: 'Estádio Poliesportivo',
    category: 'parks',
    cost: 3500,
    monthlyUpkeep: 160,
    powerConsumed: 50,
    waterConsumed: 40,
    parkEffect: 90,
    radiusEffect: 18,
    description: 'Atrai turismo em massa, jogos memoráveis e enorme satisfação popular.',
    iconName: 'Trophy',
    size: 2,
  },
  // Zone simulation buildings (auto-spawned)
  res_low_1: {
    id: 'res_low_1',
    name: 'Casa Unifamiliar Térrea',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 3,
    waterConsumed: 3,
    description: 'Residência simples de madeira com jardim modesto.',
    iconName: 'Home',
    size: 1,
  },
  res_low_2: {
    id: 'res_low_2',
    name: 'Sobrado de Alvenaria',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 6,
    waterConsumed: 5,
    description: 'Sobrado familiar bem cuidado com garagem.',
    iconName: 'Home',
    size: 1,
  },
  res_med_1: {
    id: 'res_med_1',
    name: 'Edifício Residencial Baixo',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 14,
    waterConsumed: 12,
    description: 'Prédio de 4 andares com múltiplos apartamentos.',
    iconName: 'Building',
    size: 1,
  },
  res_med_2: {
    id: 'res_med_2',
    name: 'Condomínio Residencial Moderno',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 22,
    waterConsumed: 18,
    description: 'Bloco residencial arborizado com piscina e varandas.',
    iconName: 'Building',
    size: 1,
  },
  res_high_1: {
    id: 'res_high_1',
    name: 'Torre Residencial Panorâmica',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 40,
    waterConsumed: 35,
    description: 'Edifício alto de alto padrão com vista privilegiada.',
    iconName: 'Building2',
    size: 1,
  },
  res_high_2: {
    id: 'res_high_2',
    name: 'Arranha-céu de Luxo Residencial',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 65,
    waterConsumed: 55,
    description: 'Imponente torre envidraçada para centenas de famílias de alta renda.',
    iconName: 'Building2',
    size: 1,
  },
  com_low_1: {
    id: 'com_low_1',
    name: 'Padaria e Mercadinho de Bairro',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 5,
    waterConsumed: 4,
    description: 'Pequeno comércio de conveniência local.',
    iconName: 'Store',
    size: 1,
  },
  com_low_2: {
    id: 'com_low_2',
    name: 'Cafeteria e Lojas Comerciais',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 10,
    waterConsumed: 8,
    description: 'Galeria comercial movimentada com serviços variados.',
    iconName: 'Store',
    size: 1,
  },
  com_med_1: {
    id: 'com_med_1',
    name: 'Centro Empresarial e Lojas',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 25,
    waterConsumed: 20,
    description: 'Edifício de escritórios e consultórios com térreo comercial.',
    iconName: 'Building',
    size: 1,
  },
  com_high_1: {
    id: 'com_high_1',
    name: 'Torre Corporativa Financeira',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 60,
    waterConsumed: 45,
    description: 'Sede de bancos, multinacionais e tecnologia de ponta.',
    iconName: 'Building2',
    size: 1,
  },
  ind_low_1: {
    id: 'ind_low_1',
    name: 'Oficina Mecânica e Galpão',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 8,
    waterConsumed: 6,
    pollutionProduced: 12,
    description: 'Pequeno entreposto de manutenção e estocagem.',
    iconName: 'Wrench',
    size: 1,
  },
  ind_med_1: {
    id: 'ind_med_1',
    name: 'Fábrica Manufatureira',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 24,
    waterConsumed: 20,
    pollutionProduced: 28,
    description: 'Linha de produção industrial com chaminés ativas.',
    iconName: 'Factory',
    size: 1,
  },
  ind_high_1: {
    id: 'ind_high_1',
    name: 'Complexo Petroquímico e Pesado',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 55,
    waterConsumed: 45,
    pollutionProduced: 60,
    description: 'Produção em larga escala de insumos básicos com alta fumaça.',
    iconName: 'Factory',
    size: 1,
  },
  ind_high_tech: {
    id: 'ind_high_tech',
    name: 'Laboratório de Robótica e Chips',
    category: 'zone',
    cost: 0,
    monthlyUpkeep: 0,
    powerConsumed: 45,
    waterConsumed: 25,
    pollutionProduced: 4,
    description: 'Indústria 4.0 limpa e de altíssimo valor agregado.',
    iconName: 'Cpu',
    size: 1,
  },
  rubble: {
    id: 'rubble',
    name: 'Escombros e Ruínas',
    category: 'special',
    cost: 0,
    monthlyUpkeep: 0,
    description: 'Restos de uma construção destruída. Use o trator (Bulldozer) para limpar.',
    iconName: 'Shovel',
    size: 1,
  },
  fire: {
    id: 'fire',
    name: 'Incêndio Ativo!',
    category: 'special',
    cost: 0,
    monthlyUpkeep: 0,
    description: 'Fogo descontrolado que pode se alastrar para vizinhos!',
    iconName: 'Flame',
    size: 1,
  },
};

export const ZONE_COSTS = {
  residential: 50,
  commercial: 60,
  industrial: 40,
  clear: 15,
};
